version: '3.1'

services:
  gateway:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5000:5000

networks:
  default:
    external:
      name: individualproject