# Generated by Django 3.1.3 on 2022-05-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.BigIntegerField(default=-1),
            preserve_default=False,
        ),
    ]
