apiVersion: apps/v1
kind: Deployment
metadata:
  name: groups-db
  labels:
    app: groups-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: groups-db
  template:
    metadata:
      labels:
        app: groups-db
    spec:
      containers:
        - name: groups-db
          image: mysql:5.7.22
          env:
            - name: MYSQL_DATABASE
              value: groupsdb
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              value: root
            - name: MYSQL_ROOT_PASSWORD
              value: root
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: databasedata
          ports:
            - containerPort: 3306
      volumes:
        - name: databasedata
          hostPath:
            path: /.databasedata
            type: DirectoryOrCreate
