version: '3.8'
services:
  groups:
    build: 
      context: .
      dockerfile: Dockerfile
    command: 'python manage.py runserver 0.0.0.0:8000'
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - groupsdb

  queue:
    build: 
      context: .
      dockerfile: Dockerfile
    command: 'python consumer.py'
    depends_on:
      - groupsdb

  groupsdb:
    image: mysql:5.7.22
    restart: always
    command: --innodb-use-native-aio=0
    environment:
      MYSQL_DATABASE: groupsdb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .databasedata:/var/lib/mysql
    ports:
      - 33067:3306

networks:
  default:
    external:
      name: individualproject