name: User API Deploy Workflow

on:
  workflow_run:
    workflows: [Django main workflow]
    types:
      - completed
jobs:
  build-and-push-user-api:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: azure/docker-login@v1
        with:
          login-server: musicappreg.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          cd users
          docker build . -t musicappreg.azurecr.io/music-app-users:latest
          docker push musicappreg.azurecr.io/music-app-users:latest
