name: Django main workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  call-base-workflow-for-groups:
    uses: Njols/music-app-backend/.github/workflows/django-reusable-workflow.yml@main
    with:
      main-folder-name: groups

  call-base-workflow-for-users:
    uses: Njols/music-app-backend/.github/workflows/django-reusable-workflow.yml@main
    with:
      main-folder-name: users

  build-and-push-user-api:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: azure/docker-login@v1
        with:
          login-server: musicappreg.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          cd users
          docker build . -t musicappreg.azurecr.io/music-app-users:latest
          docker push musicappreg.azurecr.io/music-app-users:latest
